### ISSUE TITLE
Add a new prop to menu items in SDDropDownMenu to hold values

### ISSUE THREAD

**Issue by coralvanda** [StratoDem/sd-material-ui#32]
Add a new prop to menu items in SDDropDownMenu to hold values

Sometimes data will be sent as part of the options, but it may not be in a human-readable form. Use a new prop field to hold that data for passing around inside an app.

**Comment by mjclawar** [comment]
This may be fixed by changing the `value` type in `PropTypes` to `any`, like in http://www.material-ui.com/#/components/dropdown-menu instead of just having it be `PropTypes.number` (seems like the implementation in this project creates the issue from the generation of `metadata.json` via Dash, rather than the `DropdownMenu` not supporting a non-numeric `value` prop).
