### ISSUE TITLE
Styling sd_material_ui.Dialog overflow

### ISSUE THREAD

**Issue by jgquach3** [StratoDem/sd-material-ui#95]
Hi, I'm using sd-material-ui with Dash and was trying to style the dialog component, specifically the overflow-y of it. I saw the other post on the dialog width, but I cannot seem to target the exact div. I have tried using external css and targeting the classname, but that doesn't seem to work either. Are there any alternatives to style this?

**Comment by coralvanda** [comment]
It's tricky, because the div that needs the `overflow` property is not the same div that receives the `classname` when you add it in your Python code. You'll need to use CSS to target divs within divs (the browser's inspect tool can help with finding the right one). Once you find the right one, though, it will work. At this point, I don't think there's any other way to make these kinds of style changes. If we can find a way, or a new way becomes possible with future changes, then we'll add it, but I'm not sure that is likely to happen very soon.

![overflow](https://user-images.githubusercontent.com/16080662/51608915-c781e180-1ee6-11e9-9227-fd98ccc303d2.gif)

**Comment by ONLYstcm** [comment]
I've been having this issue myself, I managed to find the div that is blocking the 'overflow-y' style but I do not know how to access it through python as that div does not even have an id.

**Comment by coralvanda** [comment]
You cannot access it through Python, and will need to use CSS. Let's say the format looks like this:

```HTML
<div classname="my-container">
  <div>
    <div>  <!--pretend this is the one that needs the style -->
    </div>
  </div>
</div>
```
You would then need CSS that looks something like this:

```CSS
.my-container > div > div {
  overflow-y: scroll;
}
```

**Comment by ONLYstcm** [comment]
I actually tried that but it still gets overwritten as shown below:

![image](https://user-images.githubusercontent.com/26184198/64178162-410c8580-ce61-11e9-8d22-8d77a5431bd1.png)

The format is currently like this:

![image](https://user-images.githubusercontent.com/26184198/64178346-9cd70e80-ce61-11e9-8b6a-89fae6d18428.png)

**Comment by coralvanda** [comment]
Ok. Thanks, that's very helpful to see. In this case, you will likely need to add the important flag. The CSS would look something like this:

```CSS
.my-container > div > div {
  overflow-y: scroll !important;
}
```

**Comment by ONLYstcm** [comment]
@coralvanda Thanks. I had been playing with so many different style elements, but couldn't find the right combination. Even though !important is often discouraged it works for me. Finally! Thanks again.
